### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by itinquark000** [aspeakman/SolisControl#1]
Hi there, 

Congrats for the job! I am leaving out of UK so Octopus file is not for me but the inverter control yes.

I have Solis RHI-3P8K-HVES-5G hybrid inverter and S3 Wifi dartalogger, from which i want to read charge/discharge data and later control charge and discharge by HA. 

I am not sure where i should install the SolisControl-main folder i download as zip. Should be inside custom_components folder? or maybe under custom_components\Solis folder? 

I cannot understand if this is supposed to be a new device integration or additional function of existing Solis integration.

Sorry in advance, since i am learning but despite reading a lot i have still doubts :)

Regards,

**Comment by aspeakman** [comment]
SolisControl is a standard Python package (independent of Home Assistant) - so I would read about installing and running it on your local computer first. The README tells you where to start by configuring 'secrets.yaml' and running 'python solis_control_req_mod.py'.

For use within Home Assistant there is a separate app 'solis_flux_times.py'. This uses SolisControl modules internally and is dependent on the HA Pyscript integration. If your provider has a cheap rate charging period and a peak rate discharge period you can use it as is, but otherwise you will need to adapt it.

**Comment by itinquark000** [comment]
Thanks @aspeakman ! i am trying to run solis_control_req_mod.py but i am facing this error:
![image](https://github.com/user-attachments/assets/b3f91d70-e36d-4c84-b58d-cf2197be8524)
Any idea how to fix it?

**Comment by aspeakman** [comment]
Possibly your  secrets.yaml or main.yaml are wrongly specified. Try https://www.yamllint.com/

**Comment by aspeakman** [comment]
The config.update() is expecting 'secrets' to be a dictionary - but it looks like it is a string or a list. I would add in print() statements to debug this.

**Comment by itinquark000** [comment]
@aspeakman Thanks! 

As u suggested i had a problem in 'secrets.yaml', now it is working and finally was able to run 'solis_control_req_mod.py'. I can read inverter charging/discharging data and send to it fixed charging/discharging data, which is brilliant. 
Now i started to deal with 'solis_flux_times.py' to make the chargin/discharging process depending on Solcast forecasts and battery status. To do that i copied all files to \config\pyscript\apps, but when running 'solis_flux_times.py' i get error: 
NameError: name 'pyscript' is not defined
![image](https://github.com/user-attachments/assets/d5f25da5-dc55-4bd5-8996-690756acb41a)

If i copy to apps folder only 'solis_flux_times.py' and to folder module both 'solis_control_req_mod.py' and 'solis_common' then i get error: ModuleNotFoundError: No module named 'solis_control_req_mod'
Therefore all files are now into apps folder.

Here some screenshots:
![image](https://github.com/user-attachments/assets/c730f39a-a68f-475d-b1a7-7d839bef6c2b)
![image](https://github.com/user-attachments/assets/3ab2d014-5516-440e-ac94-455ac5d2cda9)
![image](https://github.com/user-attachments/assets/91b5a8bd-b3d3-4aea-a153-20a338703ae8)

I gave a look here https://hacs-pyscript.readthedocs.io/en/stable/reference.html but i am not sure what to do.

Could you pls suggest where the problem could be? Many thanks in advance.

**Comment by aspeakman** [comment]
In your configuration.yaml put
```pyscript: !include pyscript/config.yaml```
In your main pyscript/ directory put secrets.yaml and config.yaml
In your pyscript/apps directory put solis_flux_times.py
In your pyscript/modules directory put solis_common.py and solis_req_mod.py
I have updated the README on this

**Comment by itinquark000** [comment]
@aspeakman unfortunately this is not working for me. If in the folder apps i put 'solis_flux_times.py' and in the folder modules i put 'solis_common.py' and 'solis_control_req_mod.py' then i get error: ModuleNotFoundError: No module named 'solis_control_req_mod'. 

Here are print screens:
![image](https://github.com/user-attachments/assets/4c186d83-9a4a-4720-8bec-9c0a5c267161)

![image](https://github.com/user-attachments/assets/ab43edb4-3053-4ec5-a76d-14fa893c0583)

![image](https://github.com/user-attachments/assets/25f2265e-892d-4174-8585-17111a53285f)

![image](https://github.com/user-attachments/assets/c837647b-473e-4af4-8976-0d42ccf7016a)

Files '__init__.py' and 'main.py' are not present at all.

The config.yaml file in the main pyscript directory is the one containing the configuration of solis_flux_times.

If then as a test i try to put all above files together into pyscript/apps folder then i get again the message: NameError: name 'pyscript' is not defined

I believe there is a problem with imports, but i cannot figure out where.

**Comment by itinquark000** [comment]
@aspeakman i do not exactly why, but even i via terminal i get above error ModuleNotFoundError: No module named 'solis_control_req_mod' i see charge/discharge values on inverter are changing, so seems to work. 
So thanks a lot for your precious help!

I am trying now to set morning_requirement as input_number.morning _requirement, so that i can change this number outside file editor, and in a not far future also make it automatic (by now far out of my HA capabilities). I am now it set this way, but not working: 
![image](https://github.com/user-attachments/assets/a56294b9-4947-4ad9-aec4-539b43bc2f54)

How should i correctly write this line to have it as a parameter?

**Comment by aspeakman** [comment]
Add quotes -> morning_requirement: 'input_number.morning_requirement'

**Comment by itinquark000** [comment]
Many thanks, it is working nicely.
