### ISSUE TITLE
Charging time schedule 

### ISSUE THREAD

**Issue by itinquark000** [aspeakman/SolisControl#3]
Dear @aspeakman ,

At the moment i have set a charge time schedule (04:00-07:00, matching provider cheap rate period) with random start. It means that within the charge window the program choose itself when to start and when to finish charging. 

To be able to match my house power supply parameters (limited amps) i cannot choose a big number of amps for charging, so i need to operate with lower amps but for longer time (wider charge window) to charge the battery properly. 

This brings to the situation that the program  starts to charge i.e. from 04:30 to 05:50. This leaves an empty bunch of time (05:50-07:00) when the battery is not charged and, at opposite, it is used by the house (discharging due to loads). As an affect at 07:00 i have a lower battery level then i would like.

Is therefore possible to edit the program so that it will choose by itself the charging start (within of course given by me window) but will end charging at the end of cheap rate window ( in my case at 07:00)?

Thanks in advance!

**Comment by itinquark000** [comment]
That will not always work. The limit is full battery; when the battery reaches 100% , then it will stop charging and still will have bunch of time till the end of charge period (i tested it).

Any other proposition?

**Comment by aspeakman** [comment]
There is now a _sync_ parameter in each charge/discharge_period which controls whether activity is tied to the 'start' or 'end' or takes place randomly within the time period.

Update all files from the repo then restart

**Comment by itinquark000** [comment]
Working fine for me, thank for great support! I am very happy
